name: Publish Release
on:
  workflow_dispatch:
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle Caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle Wrapper
        run: chmod +x gradlew

      - name: Get Version
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./gradle.properties"
          properties: "version"

      - name: Publish Release
        run: ./gradlew publish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload NeoForge Releases (Curse/Modrinth)
        id: neoforge_release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSE_ID }}
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: ./neoforge/build/libs/!(*-@(dev-shadow|sources)).jar
          name: "[NeoForge] Golem Overhaul ${{ steps.properties.outputs.version }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: changelog.md

      - name: Upload Fabric Releases (Curse/Modrinth)
        id: fabric_release
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: ${{ vars.CURSE_ID }}
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: ./fabric/build/libs/!(*-@(dev-shadow|sources)).jar
          name: "[Fabric] Golem Overhaul ${{ steps.properties.outputs.version }}"
          version: ${{ steps.properties.outputs.version }}
          version-type: release
          changelog-file: changelog.md